-- Add common foods without replacing existing labels or aliases.
WITH catalogue(name, name_cs, aliases_en, aliases_cs) AS (VALUES
('Potato', 'Brambora', 'potatoes', 'brambory'),
('Sweet potato', 'Batát', 'sweet potatoes', 'batáty;sladké brambory'),
('Broccoli', 'Brokolice', '', ''),
('Cauliflower', 'Květák', '', ''),
('Spinach', 'Špenát', '', ''),
('Kale', 'Kadeřávek', '', 'kadeřavá kapusta'),
('White cabbage', 'Bílé zelí', 'green cabbage', ''),
('Red cabbage', 'Červené zelí', 'purple cabbage', ''),
('Savoy cabbage', 'Kapusta', '', 'hlávková kapusta'),
('Brussels sprouts', 'Růžičková kapusta', 'brussel sprouts', ''),
('Lettuce', 'Hlávkový salát', '', ''),
('Romaine lettuce', 'Římský salát', 'cos lettuce', ''),
('Iceberg lettuce', 'Ledový salát', '', ''),
('Arugula', 'Rukola', 'rocket', ''),
('Lambs lettuce', 'Polníček', 'corn salad', 'kozlíček polníček'),
('Celery stalks', 'Řapíkatý celer', 'celery stalk;celery sticks', ''),
('Celeriac', 'Bulvový celer', 'celery root', 'celer'),
('Parsley root', 'Kořenová petržel', '', 'petržel kořen'),
('Parsnip', 'Pastinák', 'parsnips', ''),
('Beetroot', 'Červená řepa', 'beets;beet', 'řepa'),
('Radish', 'Ředkvička', 'radishes', 'ředkvičky'),
('White radish', 'Bílá ředkev', 'daikon', ''),
('Turnip', 'Vodnice', 'turnips', ''),
('Leek', 'Pórek', 'leeks', 'pór'),
('Shallot', 'Šalotka', 'shallots', 'šalotky'),
('Red onion', 'Červená cibule', 'red onions', ''),
('Eggplant', 'Lilek', 'aubergine;eggplants;aubergines', 'baklažán'),
('Pumpkin', 'Dýně', 'pumpkins', ''),
('Butternut squash', 'Máslová dýně', '', ''),
('Asparagus', 'Chřest', '', ''),
('Green peas', 'Zelený hrášek', 'peas', 'hrášek'),
('Green beans', 'Zelené fazolky', 'green bean;string beans', 'fazolové lusky'),
('Sweetcorn', 'Kukuřice', 'sweet corn;corn kernels', ''),
('Fennel bulb', 'Bulvový fenykl', '', ''),
('Artichoke', 'Artyčok', 'artichokes', 'artyčoky'),
('Button mushrooms', 'Žampiony', 'button mushroom;white mushrooms', 'žampion'),
('Oyster mushrooms', 'Hlíva ústřičná', 'oyster mushroom', 'hlíva'),
('Shiitake mushrooms', 'Houby shiitake', 'shiitake', 'šitake'),
('Porcini mushrooms', 'Hřiby', 'porcini;porcini mushroom', 'hřib'),
('Sauerkraut', 'Kysané zelí', '', 'kvašené zelí'),
('Pickled cucumbers', 'Nakládané okurky', 'gherkins;pickles', 'kyselé okurky'),
('Garlic powder', 'Sušený česnek', 'powdered garlic', 'česnekový prášek'),
('Fresh ginger', 'Čerstvý zázvor', 'ginger root', 'zázvor'),
('Chilli pepper', 'Chilli paprička', 'chili pepper;chilli peppers;chili peppers', 'chilli papričky'),
('Apple', 'Jablko', 'apples', 'jablka'),
('Pear', 'Hruška', 'pears', 'hrušky'),
('Orange', 'Pomeranč', 'oranges', 'pomeranče'),
('Mandarin', 'Mandarinka', 'mandarins;tangerine;tangerines', 'mandarinky'),
('Grapefruit', 'Grapefruit', 'grapefruits', 'grep'),
('Lime', 'Limetka', 'limes', 'limetky'),
('Plum', 'Švestka', 'plums', 'švestky'),
('Apricot', 'Meruňka', 'apricots', 'meruňky'),
('Nectarine', 'Nektarinka', 'nectarines', 'nektarinky'),
('Sweet cherries', 'Třešně', 'sweet cherry;cherries', 'třešeň'),
('Sour cherries', 'Višně', 'sour cherry', 'višeň'),
('Blueberries', 'Borůvky', 'blueberry', 'borůvka'),
('Raspberries', 'Maliny', 'raspberry', 'malina'),
('Blackberries', 'Ostružiny', 'blackberry', 'ostružina'),
('Redcurrants', 'Červený rybíz', 'red currants;redcurrant', ''),
('Blackcurrants', 'Černý rybíz', 'black currants;blackcurrant', ''),
('Cranberries', 'Klikva', 'cranberry', 'klikvy'),
('Grapes', 'Hroznové víno', 'grape', 'hrozny'),
('Kiwi', 'Kiwi', 'kiwifruit', ''),
('Mango', 'Mango', 'mangoes;mangos', ''),
('Pineapple', 'Ananas', 'pineapples', ''),
('Watermelon', 'Vodní meloun', 'watermelons', ''),
('Cantaloupe', 'Meloun cantaloupe', '', ''),
('Pomegranate', 'Granátové jablko', 'pomegranates', 'granátová jablka'),
('Dates', 'Datle', 'date fruit', ''),
('Raisins', 'Rozinky', 'sultanas', 'hrozinky'),
('Dried apricots', 'Sušené meruňky', 'dried apricot', ''),
('Prunes', 'Sušené švestky', 'prune', ''),
('Dried figs', 'Sušené fíky', 'dried fig', ''),
('Chicken thigh', 'Kuřecí stehno', 'chicken thighs', 'kuřecí stehna'),
('Whole chicken', 'Celé kuře', '', ''),
('Turkey breast', 'Krůtí prsa', 'turkey breasts', 'krůtí prso'),
('Ground turkey', 'Mleté krůtí maso', 'turkey mince', ''),
('Pork tenderloin', 'Vepřová panenka', '', ''),
('Pork shoulder', 'Vepřová plec', '', ''),
('Pork loin', 'Vepřová pečeně', '', 'vepřová kotleta'),
('Ground pork', 'Mleté vepřové maso', 'pork mince', ''),
('Beef sirloin', 'Hovězí roštěná', 'sirloin steak', ''),
('Beef chuck', 'Hovězí plec', 'chuck steak', ''),
('Lamb leg', 'Jehněčí kýta', 'leg of lamb', ''),
('Duck breast', 'Kachní prsa', 'duck breasts', 'kachní prso'),
('Rabbit meat', 'Králičí maso', '', ''),
('Chicken liver', 'Kuřecí játra', 'chicken livers', ''),
('Bacon', 'Slanina', '', ''),
('Ham', 'Šunka', '', ''),
('Sausage', 'Klobása', 'sausages', 'klobásy'),
('Cod fillet', 'Filet z tresky', 'cod fillets;cod', 'treska'),
('Trout', 'Pstruh', '', ''),
('Mackerel', 'Makrela', '', ''),
('Sardines', 'Sardinky', 'sardine', ''),
('Smoked salmon', 'Uzený losos', '', ''),
('Shrimp', 'Krevety', 'shrimps;prawns;prawn', 'kreveta'),
('Mussels', 'Slávky', 'mussel', ''),
('Squid', 'Oliheň', 'calamari', 'oliheň obecná'),
('Anchovies', 'Ančovičky', 'anchovy', 'ančovička'),
('Plain yogurt', 'Bílý jogurt', 'plain yoghurt;natural yogurt;natural yoghurt', ''),
('Skyr', 'Skyr', '', ''),
('Quark', 'Tvaroh', '', ''),
('Kefir', 'Kefír', '', ''),
('Buttermilk', 'Podmáslí', '', ''),
('Sour cream', 'Zakysaná smetana', '', ''),
('Whipping cream', 'Smetana ke šlehání', 'heavy cream;double cream', 'šlehačka'),
('Cooking cream', 'Smetana na vaření', 'single cream', ''),
('Cream cheese', 'Smetanový sýr', '', 'čerstvý smetanový sýr'),
('Mozzarella', 'Mozzarella', '', ''),
('Cheddar', 'Čedar', 'cheddar cheese', 'cheddar'),
('Gouda', 'Gouda', '', ''),
('Edam', 'Eidam', 'edam cheese', ''),
('Parmesan', 'Parmazán', 'parmigiano reggiano;parmesan cheese', 'parmezán'),
('Feta', 'Feta', 'feta cheese', ''),
('Goat cheese', 'Kozí sýr', 'goats cheese', ''),
('Ricotta', 'Ricotta', '', ''),
('Mascarpone', 'Mascarpone', '', ''),
('Halloumi', 'Halloumi', '', ''),
('Blue cheese', 'Sýr s modrou plísní', '', 'niva'),
('Egg whites', 'Vaječné bílky', 'egg white', 'bílek;bílky'),
('Egg yolks', 'Vaječné žloutky', 'egg yolk', 'žloutek;žloutky'),
('Rice', 'Rýže', 'white rice', 'bílá rýže'),
('Brown rice', 'Hnědá rýže', 'wholegrain rice', 'celozrnná rýže;natural rýže'),
('Basmati rice', 'Rýže basmati', 'basmati', ''),
('Jasmine rice', 'Jasmínová rýže', 'jasmine', ''),
('Arborio rice', 'Rýže arborio', 'risotto rice', 'rýže na rizoto'),
('Pasta', 'Těstoviny', '', ''),
('Spaghetti', 'Špagety', '', ''),
('Penne', 'Penne', '', ''),
('Wholewheat pasta', 'Celozrnné těstoviny', 'whole wheat pasta;wholegrain pasta', ''),
('Rice noodles', 'Rýžové nudle', '', ''),
('Couscous', 'Kuskus', '', ''),
('Bulgur', 'Bulgur', '', ''),
('Quinoa', 'Quinoa', '', ''),
('Buckwheat', 'Pohanka', '', ''),
('Millet', 'Jáhly', '', ''),
('Pearl barley', 'Ječné kroupy', '', 'kroupy'),
('Polenta', 'Polenta', 'cornmeal', 'kukuřičná krupice'),
('Semolina', 'Krupice', 'wheat semolina', 'pšeničná krupice'),
('Plain flour', 'Hladká mouka', 'all purpose flour;all-purpose flour', ''),
('Semi-coarse flour', 'Polohrubá mouka', '', ''),
('Coarse flour', 'Hrubá mouka', '', ''),
('Wholewheat flour', 'Celozrnná mouka', 'whole wheat flour', ''),
('Rye flour', 'Žitná mouka', '', ''),
('Spelt flour', 'Špaldová mouka', '', ''),
('Rice flour', 'Rýžová mouka', '', ''),
('Almond flour', 'Mandlová mouka', '', ''),
('Cornstarch', 'Kukuřičný škrob', 'corn starch', ''),
('Potato starch', 'Bramborový škrob', '', 'solamyl'),
('Breadcrumbs', 'Strouhanka', 'bread crumbs', ''),
('Bread', 'Chléb', '', 'chleba'),
('Wholegrain bread', 'Celozrnný chléb', 'whole grain bread', ''),
('Rye bread', 'Žitný chléb', '', ''),
('Bread roll', 'Rohlík', 'bread rolls', 'rohlíky'),
('Tortilla', 'Tortilla', 'tortillas;wraps', ''),
('Pita bread', 'Pita chléb', 'pitta bread', ''),
('Chickpeas', 'Cizrna', 'chickpea;garbanzo beans', ''),
('Green lentils', 'Zelená čočka', '', ''),
('Brown lentils', 'Hnědá čočka', '', ''),
('Kidney beans', 'Červené fazole', '', ''),
('White beans', 'Bílé fazole', 'cannellini beans', ''),
('Black beans', 'Černé fazole', '', ''),
('Split peas', 'Loupaný hrách', '', 'půlený hrách'),
('Edamame', 'Edamame', 'green soybeans', ''),
('Tempeh', 'Tempeh', '', ''),
('Silken tofu', 'Hedvábné tofu', 'soft tofu', ''),
('Smoked tofu', 'Uzené tofu', '', ''),
('Soy milk', 'Sójový nápoj', 'soya milk;soy drink', 'sójové mléko'),
('Oat milk', 'Ovesný nápoj', 'oat drink', 'ovesné mléko'),
('Almond milk', 'Mandlový nápoj', 'almond drink', 'mandlové mléko'),
('Almonds', 'Mandle', 'almond', ''),
('Hazelnuts', 'Lískové ořechy', 'hazelnut', 'lískový ořech'),
('Cashews', 'Kešu', 'cashew;cashew nuts', 'kešu ořechy'),
('Peanuts', 'Arašídy', 'peanut;groundnuts', 'burské oříšky'),
('Pistachios', 'Pistácie', 'pistachio', ''),
('Pecans', 'Pekanové ořechy', 'pecan', ''),
('Pine nuts', 'Piniové oříšky', 'pine nut', ''),
('Sunflower seeds', 'Slunečnicová semínka', 'sunflower seed', ''),
('Pumpkin seeds', 'Dýňová semínka', 'pumpkin seed', ''),
('Sesame seeds', 'Sezamová semínka', 'sesame seed', ''),
('Chia seeds', 'Chia semínka', 'chia', ''),
('Flaxseed', 'Lněné semínko', 'flax seeds;linseed', 'lněná semínka'),
('Poppy seeds', 'Mák', 'poppy seed', ''),
('Desiccated coconut', 'Strouhaný kokos', 'shredded coconut', ''),
('Tahini', 'Tahini', 'sesame paste', 'sezamová pasta'),
('Sunflower oil', 'Slunečnicový olej', '', ''),
('Rapeseed oil', 'Řepkový olej', 'canola oil', ''),
('Coconut oil', 'Kokosový olej', '', ''),
('Ghee', 'Přepuštěné máslo', 'clarified butter', 'ghí'),
('Lard', 'Sádlo', '', ''),
('Sugar', 'Cukr', 'white sugar;granulated sugar', 'cukr krystal;krupicový cukr'),
('Brown sugar', 'Hnědý cukr', '', ''),
('Icing sugar', 'Moučkový cukr', 'powdered sugar;confectioners sugar', 'cukr moučka'),
('Maple syrup', 'Javorový sirup', '', ''),
('Cocoa powder', 'Kakaový prášek', 'cocoa', 'kakao'),
('Dark chocolate', 'Hořká čokoláda', '', ''),
('Baking powder', 'Kypřicí prášek', '', 'prášek do pečiva'),
('Baking soda', 'Jedlá soda', 'bicarbonate of soda', ''),
('Fresh yeast', 'Čerstvé droždí', '', 'droždí'),
('Dried yeast', 'Sušené droždí', 'instant yeast;active dry yeast', ''),
('Vanilla extract', 'Vanilkový extrakt', '', ''),
('Vanilla sugar', 'Vanilkový cukr', '', ''),
('Gelatin', 'Želatina', 'gelatine', ''),
('Tomato paste', 'Rajčatový protlak', '', 'rajský protlak'),
('Passata', 'Pasírovaná rajčata', 'tomato passata', ''),
('Ketchup', 'Kečup', 'catsup', ''),
('Mustard', 'Hořčice', '', ''),
('Dijon mustard', 'Dijonská hořčice', '', ''),
('Mayonnaise', 'Majonéza', 'mayo', ''),
('Balsamic vinegar', 'Balzamikový ocet', '', 'balsamico'),
('Apple cider vinegar', 'Jablečný ocet', 'cider vinegar', ''),
('White wine vinegar', 'Bílý vinný ocet', '', ''),
('Rice vinegar', 'Rýžový ocet', '', ''),
('Fish sauce', 'Rybí omáčka', '', ''),
('Worcestershire sauce', 'Worcesterská omáčka', 'worcester sauce', 'worcester'),
('Pesto', 'Pesto', '', ''),
('Olives', 'Olivy', 'olive', 'oliva'),
('Capers', 'Kapary', 'caper', ''),
('Chicken stock', 'Kuřecí vývar', 'chicken broth', ''),
('Beef stock', 'Hovězí vývar', 'beef broth', ''),
('Parsley', 'Petrželová nať', 'flat leaf parsley;curly parsley', 'nať petržele'),
('Basil', 'Bazalka', '', ''),
('Oregano', 'Oregano', '', 'dobromysl'),
('Thyme', 'Tymián', '', ''),
('Rosemary', 'Rozmarýn', '', 'rozmarýna'),
('Chives', 'Pažitka', '', ''),
('Mint', 'Máta', '', ''),
('Fresh coriander', 'Čerstvý koriandr', 'cilantro;coriander leaves', 'koriandrová nať'),
('Bay leaf', 'Bobkový list', 'bay leaves', ''),
('Marjoram', 'Majoránka', '', ''),
('Sweet paprika', 'Sladká paprika', 'paprika powder', 'mletá sladká paprika'),
('Chilli flakes', 'Chilli vločky', 'chili flakes;red pepper flakes', ''),
('Cayenne pepper', 'Kajenský pepř', 'cayenne', ''),
('Turmeric', 'Kurkuma', '', ''),
('Ground coriander', 'Mletý koriandr', 'coriander powder', ''),
('Caraway seeds', 'Kmín', 'caraway', 'kmín kořenný'),
('Nutmeg', 'Muškátový oříšek', '', ''),
('Cloves', 'Hřebíček', '', ''),
('Allspice', 'Nové koření', '', ''),
('Cardamom', 'Kardamom', '', ''),
('Curry powder', 'Kari koření', '', 'kari'),
('Garam masala', 'Garam masala', '', '')
), added AS (
  INSERT INTO ingredients (name, is_catalog)
  SELECT name, true FROM catalogue
  ON CONFLICT (name) DO UPDATE SET is_catalog = true
  RETURNING id, name
)
INSERT INTO ingredient_translations (ingredient_id, locale, name, aliases)
SELECT added.id, translation.locale, translation.name,
  ARRAY(SELECT DISTINCT lower(trim(alias)) FROM unnest(string_to_array(translation.aliases, ';')) alias WHERE trim(alias) <> '')
FROM added JOIN catalogue ON catalogue.name = added.name
CROSS JOIN LATERAL (VALUES
  ('en', catalogue.name, catalogue.aliases_en),
  ('cs', catalogue.name_cs, catalogue.aliases_cs)
) translation(locale, name, aliases)
ON CONFLICT (ingredient_id, locale) DO NOTHING;
