@base = http://localhost:3000

### List meals
GET {{base}}/meals

### Create meal
POST {{base}}/meals
Content-Type: application/json

{
  "name": "Chicken Rice Bowl",
  "calories": 550,
  "proteinG": 45,
  "carbsG": 60,
  "fatG": 10,
  "fiberG": 7,
  "sugarG": 5,
  "saturatedFatG": 2.5,
  "saltG": 1.2
}
