global:
  scrape_interval: 15s

scrape_configs:
  - job_name: meal-plan
    metrics_path: /metrics
    authorization:
      credentials: __METRICS_TOKEN__
    static_configs:
      - targets: ['app:3000']
