@base = http://localhost:3000
@mealId = 1

### Update meal (partial)
PATCH {{base}}/meals/{{mealId}}
Content-Type: application/json

{
  "calories": 600,
  "proteinG": 48,
  "fiberG": 8.5,
  "sugarG": 6,
  "saturatedFatG": 4.2,
  "saltG": 1.1
}

### Delete meal
DELETE {{base}}/meals/{{mealId}}
